name: PluginTest
version: '${project.version}'
main: com.lucas.plugintest.PluginTest
api-version: '1.16'
commands:
  kick:
    description: kick a player from the server
  ban:
<<<<<<< HEAD
    description: ban a player from the server
  config:
  ping:
    description: print the player's latency
  mute:
    description: mute a player
  unmute:
    description: remove the mute

=======
    description: ban a player
  config:
  ping:
    description: take the ping of the player
  mute:
    description: mute a player
>>>>>>> 4a324cbdbb5284a2856e5e74d545b44f2378af90



