name: PluginTest
version: '${project.version}'
main: com.lucas.plugintest.PluginTest
api-version: '1.16'
commands:
  kick:
    description: kick a player from the server
  ban:
    description: ban a player from the server
  config:
  ping:
    description: print the player's latency
  mute:
    description: mute a player
  unmute:
    description: remove the mute
  unban:
    description: remove the ban
  vanish:
    aliases: v
    description: enter vanish mode
  tell:
    aliases:
      - message
      - whispher
  reply:
    aliases:
      - r
      - rep
  menu:


