name: PluginTest
version: '${project.version}'
main: com.lucas.plugintest.PluginTest
api-version: '1.16'
commands:
  kick:
    description: kick a player
  ban:
    description: ban a player
  config:
  ping:
    description: take the ping of the player
  mute:
    description: mute a player



