name: PluginTest
version: '${project.version}'
main: com.lucas.plugintest.PluginTest
api-version: '1.16'
commands:
  block:
    description: block someone to move
  kick:
    description: kick a player
